import { motion } from "framer-motion";
import Head from "next/head";
import Contact from "./components/contact";
import Hero from "./components/hero";
import NavBar from "./components/navbar";
import Profile from "./components/profile";
import Skills from "./components/skill";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ansar Fadillah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex flex-col font-fireCodeode">
        <Hero />
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
        >
          <Profile />
        </motion.div>
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
        >
          <Skills />
        </motion.div>
        <Contact />
      </main>
    </>
  );
}
